### ISSUE TITLE
Cannot use w TextEdit.app

### ISSUE THREAD

**Issue by chakrit** [Manoonchai/Manoonchai#1]
uname -a

```sh
Darwin GZ44.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
```

Steps:
1. Install manoonchai keylayout
2. Open TextEdit & Keyboard Viewer
3. Focus TextEdit
4. Try to switch to Manoonchai layout.

**Comment by chakrit** [comment]
Pages.app also doesn't work.

**Comment by narze** [comment]
Did you restart once? Or try installing on `/Library/Keyboard Layouts` instead of `~/Library/Keyboard Layouts` (or vice-versa)
I'm not sure if we should install on both paths or not, I've encountered this issues before too.

**Comment by narze** [comment]
Closed due to inactivity
