### ISSUE TITLE
Feature Request: xkb layout for linux users

### ISSUE THREAD

**Issue by thanatchakromsang** [Manoonchai/Manoonchai#3]
I would like to purpose an implementation of manoonchai for linux users using xkb layout

Would you mind If I send a pull request?

**Comment by hiohlan** [comment]
XKB file is still in [Kiimo](https://github.com/Manoonchai/kiimo).
[Manoonchai_xkb](https://raw.githubusercontent.com/Manoonchai/kiimo/main/output/Manoonchai_xkb)

**Comment by thanatchakromsang** [comment]
Thanks

**Comment by narze** [comment]
I'd add linux download link later, sorry for inconvenience krub 🙏
