### ISSUE TITLE
XKB file generated, but not yet included in releases or on website

### ISSUE THREAD

**Issue by toastal** [Manoonchai/Manoonchai#5]
It took me a long time to find how the files are generated https://github.com/Manoonchai/kiimo/tree/main/output -- at least this is where I'm assuming these files are located. The [merge request for XKB](https://github.com/Manoonchai/kiimo/pull/2) is merged but no new release cut. GNU/Linux and BSDs matter too. With devices like Valve's Steam Deck rolling out, it cannot be expected that all users will know how to find or install these. Being an open-source project, it's best to be a good steward and support open-source operating systems as well, even if their current market share is smaller. Let's get it added soon!

Typically keyboard layouts are installed at `/usr/share/X11/xkb/symbols/th-manoonchai` by the OS which requires `sudo` to modify, or can be locally installed to `$XDG_CONFIG_HOME/xkb/symbols/th-manoonchai`. I can't say whether or not `th` locally is appended or overrides the default `th` or if it needs a custom name though because I'm not on a tradition OS (NixOS, which has [different documentation](https://nixos.wiki/wiki/Keyboard_Layout_Customization)).

The approach with the least effort would be to include and host the `Manoonchai_xkb` with a message on the site saying something to the effect of: “Consult your distribution’s documentation on how to install custom layouts (typically `$XDG_CONFIG_HOME/xbd/symbols/…`)”. Here is the [logo](https://en.wikipedia.org/wiki/X.Org_Server#/media/File:X.Org_Logo.svg) for Xserver that could be used to cover the category in general for the site (more accurate than a Linux penguin).

**Comment by narze** [comment]
Closed as @hiohlan included it on the website. I didn't it yet as I believed it works :)
Maybe I'll ask someone to add the installation instructions 👍🏻
